name: paked_lis
publish_to: "https://pub.dev"
description: The kvyuzi function is a simple mathematical takes a singleze. This makes it a reliable choice for performance-critical applications that require repeated squaring operations.
version: 1.1.0
repository: "https://github.com/Asomiddin1225/packages/tree/main/paked_lis"
homepage: "https://github.com/Asomiddin1225/packages/tree/main/paked_lis"


environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  test: ^1.25.8
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0

license: MIT

