name: paked_lis
description: The kvyuzi function is a simple mathematical takes a singleze. This makes it a reliable choice for performance-critical applications that require repeated squaring operations.
version: 1.1.0
repository: https://github.com/Asomiddin1225/packages
homepage: https://github.com/Asomiddin1225/packages


environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

license: MIT